// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: gl.proto

package gameslobby

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MachineType int32 `protobuf:"varint,1,opt,name=MachineType,proto3" json:"MachineType,omitempty"`
}

func (x *EntryRequest) Reset() {
	*x = EntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryRequest) ProtoMessage() {}

func (x *EntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryRequest.ProtoReflect.Descriptor instead.
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return file_gl_proto_rawDescGZIP(), []int{0}
}

func (x *EntryRequest) GetMachineType() int32 {
	if x != nil {
		return x.MachineType
	}
	return 0
}

type EntryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`      // 0=處理成功 非0則對應錯誤代碼
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"` // 處理訊息
}

func (x *EntryResult) Reset() {
	*x = EntryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryResult) ProtoMessage() {}

func (x *EntryResult) ProtoReflect() protoreflect.Message {
	mi := &file_gl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryResult.ProtoReflect.Descriptor instead.
func (*EntryResult) Descriptor() ([]byte, []int) {
	return file_gl_proto_rawDescGZIP(), []int{1}
}

func (x *EntryResult) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EntryResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gl_proto protoreflect.FileDescriptor

var file_gl_proto_rawDesc = []byte{
	0x0a, 0x08, 0x67, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x22, 0x30, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x4d, 0x61, 0x63,
	0x68, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x48, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x4c, 0x6f,
	0x62, 0x62, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x6c, 0x6f,
	0x62, 0x62, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42,
	0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gl_proto_rawDescOnce sync.Once
	file_gl_proto_rawDescData = file_gl_proto_rawDesc
)

func file_gl_proto_rawDescGZIP() []byte {
	file_gl_proto_rawDescOnce.Do(func() {
		file_gl_proto_rawDescData = protoimpl.X.CompressGZIP(file_gl_proto_rawDescData)
	})
	return file_gl_proto_rawDescData
}

var file_gl_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gl_proto_goTypes = []interface{}{
	(*EntryRequest)(nil), // 0: gameslobby.EntryRequest
	(*EntryResult)(nil),  // 1: gameslobby.EntryResult
}
var file_gl_proto_depIdxs = []int32{
	0, // 0: gameslobby.GamesLobby.Entry:input_type -> gameslobby.EntryRequest
	1, // 1: gameslobby.GamesLobby.Entry:output_type -> gameslobby.EntryResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gl_proto_init() }
func file_gl_proto_init() {
	if File_gl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gl_proto_goTypes,
		DependencyIndexes: file_gl_proto_depIdxs,
		MessageInfos:      file_gl_proto_msgTypes,
	}.Build()
	File_gl_proto = out.File
	file_gl_proto_rawDesc = nil
	file_gl_proto_goTypes = nil
	file_gl_proto_depIdxs = nil
}
