// Code generated by goctl. DO NOT EDIT.
// Source: gl.proto

package server

import (
	"context"

	"game-lobby/game-lobby-server/internal/logic"
	"game-lobby/game-lobby-server/internal/svc"
	"game-lobby/game-lobby-server/types/gameslobby"
)

type GamesLobbyServer struct {
	svcCtx *svc.ServiceContext
	gameslobby.UnimplementedGamesLobbyServer
}

func NewGamesLobbyServer(svcCtx *svc.ServiceContext) *GamesLobbyServer {
	return &GamesLobbyServer{
		svcCtx: svcCtx,
	}
}

func (s *GamesLobbyServer) Entry(ctx context.Context, in *gameslobby.EntryRequest) (*gameslobby.EntryResult, error) {
	l := logic.NewEntryLogic(ctx, s.svcCtx)
	return l.Entry(in)
}
